import { format_long } from '../intl/number.ts';

import Page from '../components/Page.tsx';
import type { ContextMap } from '../context.ts';
import { get_relative_url, sanitize_did } from '../utils/url.ts';

export interface WelcomePageProps {
	ctx: ContextMap;
	path: string;
}

export function WelcomePage({ ctx, path }: WelcomePageProps) {
	let root_amount = 0;
	let replies_amount = 0;
	let post_amount = 0;
	{
		for (const [_, archive] of ctx) {
			post_amount += archive.records.posts.size;
			for (const post of archive.records.posts.values()) {
				if (post.reply === undefined) {
					root_amount++;
				} else {
					replies_amount++;
				}
			}
		}
	}

	return (
		<Page title={`Bluesky archive`} ctx={ctx} path={path}>
			<div class="WelcomePage__content">
				<h1 class="WelcomePage__header">Welcome to a Bluesky archive</h1>
				<p class="WelcomePage__paragraph">
					There are {format_long(post_amount)} posts in this archive, containing {format_long(root_amount)}{' '}
					roots and {format_long(replies_amount)} replies. Use the links at the top to navigate.
				</p>
				<p class="WelcomePage__paragraph">Accounts in this archive:</p>
				<ul class="WelcomePage__list">
					{Array.from(ctx.values()).map((archive) => (
						<li>
							<a href={get_relative_url(`/profile/${sanitize_did(archive.profile.did)}/posts/1.html`, path)}>
								<strong>{archive.profile.handle}</strong>
							</a>{' '}
							<a href={get_relative_url(`/profile/${sanitize_did(archive.profile.did)}/posts/1.html`, path)}>
								<code>{archive.profile.did}</code>
							</a>
						</li>
					))}
				</ul>
			</div>
			<div class="WelcomePage__footer">
				generated by{' '}
				<a href="https://mary-ext.github.io/skeetgen" target="_blank" class="Link">
					skeetgen
				</a>{' '}
				at {new Date().toISOString()}
			</div>
		</Page>
	);
}
